"""
state.py — Shared Pipeline State Schema for the EarningsLens LangGraph agent pipeline.

Defines the TypedDict ``PipelineState`` that flows through every node in the
LangGraph StateGraph.  Each agent reads from and writes to this shared state,
enabling transparent data handoff without coupling agent implementations.

Design notes
------------
- All fields have a default-safe type so partial state (e.g. after a single
  node has run) remains valid.
- The ``errors`` list accumulates non-fatal errors so downstream agents can
  inspect and compensate rather than crashing the pipeline.
- ``spacy_baseline_targets`` is populated by the extractor when it falls back
  to the spaCy baseline, enabling post-hoc comparison of both signals.
- ``transcript`` carries an optional structured transcript dict (NB03 v2
  shape: ``{"transcript_id", "company_id", "quarter", "components": [
  {"text", "component_type"}, ...]}``). When present, the Extractor agent
  routes through ``LLMTargetExtractor.extract_transcript`` — the same call
  NB03 v2 used to produce ``llm_targets.parquet`` — instead of the flat
  string fallback. CIQ component_type codes carried in ``components`` are:
  1=Press Release, 2=Presentation, 3=Analyst Question, 4=Management Answer.

  IMPORTANT: LangGraph only propagates fields declared in this TypedDict.
  Any state key not listed here is silently stripped at graph entry. Adding
  ``transcript`` here is what enables the Extractor agent's structured path.
"""

from __future__ import annotations

from typing import Any, Dict, List, Optional
from typing_extensions import TypedDict


class PipelineState(TypedDict, total=False):
    """
    Shared state dictionary that flows through the LangGraph agent pipeline.

    All fields are optional (total=False) so any agent can construct a partial
    state update and merge it with the running state via LangGraph's built-in
    state merging semantics.

    Fields
    ------
    transcript_text : str
        Raw earnings call transcript text to be processed (flat string).
        Always populated; used by spaCy and by the LLM extractor's flat
        fallback path.
    transcript : Dict[str, Any]
        Optional structured transcript dict in NB03 v2 shape::

            {
              "transcript_id": "<company_id>_<YYYY>Q<N>",
              "company_id"   : "<id>",
              "quarter"      : "<YYYY>Q<N>",
              "components"   : [
                  {"text": "...", "component_type": 2},
                  {"text": "...", "component_type": 3},
                  {"text": "...", "component_type": 4},
                  ...
              ],
            }

        When supplied, the Extractor agent calls
        ``LLMTargetExtractor.extract_transcript`` so each component goes
        through the LLM with its real CIQ component_type. This reproduces
        the exact targets that NB03 v2 produced for ``llm_targets.parquet``
        (and therefore the targets ChromaDB historicals were embedded
        from).
    company_id : str
        Unique company identifier (CIK, ticker, or internal ID).
    ticker : str
        Stock ticker symbol (e.g. "AAPL").
    fiscal_quarter : str
        Fiscal quarter string in "YYYYQq" format (e.g. "2023Q2").
    component_type : int
        Transcript component indicator:
            1 = prepared remarks only
            2 = Q&A only
            3 = full transcript
    extracted_targets : List[Dict]
        Targets extracted by the active extractor (LLM or spaCy fallback).
        Each target dict contains at minimum:
            metric_name : str
            context     : str
            is_financial : bool
            target_type : str ("financial" | "non-financial")
    historical_targets : List[Dict]
        Historical targets retrieved from ChromaDB for the prior 4 quarters.
        Populated by the Comparator agent.
    continuity_results : Dict
        Output of semantic continuity classification:
            maintained : List[str]  — target labels classified as maintained
            rephrased  : List[str]  — target labels classified as rephrased
            dropped    : List[str]  — target labels classified as dropped
            details    : Dict[str, Dict]  — per-target detail records
    classification_results : Dict
        Output of the Classifier agent:
            dropped_financial     : List[Dict]
            dropped_non_financial : List[Dict]
            persistent_dropped    : List[Dict]
            ephemeral_dropped     : List[Dict]
            risk_score            : float  in [0, 1]
            financial_drop_ratio  : float
            nonfinancial_drop_ratio : float
            persistent_drop_ratio : float
    report : Dict
        Structured narrative report generated by the Reporter agent:
            summary          : str   — one-paragraph risk assessment
            risk_flag        : str   — "HIGH" | "MEDIUM" | "LOW"
            dropped_targets  : List[Dict]  — table rows
            recommendation   : str   — investment implication statement
            generated_at     : str   — ISO 8601 timestamp
    spacy_baseline_targets : List[Dict]
        Targets extracted by the spaCy baseline extractor (always populated
        when the LLM extractor is used, for comparison purposes).
    errors : List[str]
        Accumulated non-fatal error messages from any agent node.
    """

    # -----------------------------------------------------------------------
    # Input fields (populated before pipeline invocation)
    # -----------------------------------------------------------------------
    transcript_text: str
    transcript: Dict[str, Any]
    company_id: str
    ticker: str
    fiscal_quarter: str
    component_type: int

    # -----------------------------------------------------------------------
    # Extractor agent input (optional fast-path)
    # -----------------------------------------------------------------------
    # When set, the Extractor agent skips the live LLM call and uses these
    # already-extracted targets directly. This is how scripts/build_demo_cache.py
    # (port of NB06) avoids re-paying for LLM tokens when llm_targets.parquet is
    # already on disk from NB03 / scripts/run_llm_extraction.py.
    pre_extracted_targets: List[Dict[str, Any]]

    # -----------------------------------------------------------------------
    # Extractor agent output
    # -----------------------------------------------------------------------
    extracted_targets: List[Dict[str, Any]]
    spacy_baseline_targets: List[Dict[str, Any]]

    # -----------------------------------------------------------------------
    # Comparator agent output
    # -----------------------------------------------------------------------
    historical_targets: List[Dict[str, Any]]
    continuity_results: Dict[str, Any]

    # -----------------------------------------------------------------------
    # Classifier agent output
    # -----------------------------------------------------------------------
    classification_results: Dict[str, Any]

    # -----------------------------------------------------------------------
    # Reporter agent output
    # -----------------------------------------------------------------------
    report: Dict[str, Any]

    # -----------------------------------------------------------------------
    # Cross-cutting concerns
    # -----------------------------------------------------------------------
    errors: List[str]


def make_initial_state(
    transcript_text: str,
    company_id: str,
    ticker: str,
    fiscal_quarter: str,
    component_type: int = 3,
    transcript: Optional[Dict[str, Any]] = None,
) -> PipelineState:
    """
    Factory function for creating a fully-initialised pipeline state.

    Initialises all list/dict fields to empty so downstream agents never
    encounter missing keys.

    Parameters
    ----------
    transcript_text:  Raw earnings call transcript text (flat string).
    company_id:       Unique company identifier.
    ticker:           Stock ticker symbol.
    fiscal_quarter:   Fiscal quarter string (e.g. "2023Q2").
    component_type:   Transcript component (1=prepared, 2=Q&A, 3=full).
    transcript:       Optional structured transcript dict (NB03 v2 shape).
                      When provided, the Extractor agent will route through
                      ``extract_transcript`` instead of the flat fallback.

    Returns
    -------
    PipelineState: Fully initialised state dict ready for pipeline invocation.
    """
    state: Dict[str, Any] = dict(
        transcript_text=transcript_text,
        company_id=company_id,
        ticker=ticker,
        fiscal_quarter=fiscal_quarter,
        component_type=component_type,
        extracted_targets=[],
        spacy_baseline_targets=[],
        historical_targets=[],
        continuity_results={
            "maintained": [],
            "rephrased": [],
            "dropped": [],
            "details": {},
        },
        classification_results={
            "dropped_financial": [],
            "dropped_non_financial": [],
            "persistent_dropped": [],
            "ephemeral_dropped": [],
            "risk_score": 0.0,
            "financial_drop_ratio": 0.0,
            "nonfinancial_drop_ratio": 0.0,
            "persistent_drop_ratio": 0.0,
        },
        report={
            "summary": "",
            "risk_flag": "LOW",
            "dropped_targets": [],
            "recommendation": "",
            "generated_at": "",
        },
        errors=[],
    )
    if transcript is not None:
        state["transcript"] = transcript
    return state  # type: ignore[return-value]
